//
//  GeneratePasswordOfferView.swift
//  PasskeyVaultAutoFill
//
//  Plan 44-05 (SAVE-02, SAVE-04). Presented ONLY from `prepareInterface(for:
//  ASGeneratePasswordsRequest)` -- the interactive generate-password path -- after `pv-ffi`'s
//  `generatePasswordFromRules` (or its safe fallback) has already produced a candidate. This
//  screen never calls into `pv-ffi`/`pv-core` itself, and confirming it (`onUse`) NEVER touches
//  `VaultAPI`/`PendingProviderItemStore`/`IdentityStoreSync` -- generating a password writes
//  nothing to the vault by itself (the header's own explicit read-only instruction, T-44-11); only
//  a later, separate SAVE-01 event, if the user actually submits the RP's form, persists anything.
//
//  Mirrors `PasskeyRegistrationConfirmView`'s own established shape (PV* tokens, tinted-slot
//  security statement, plain non-playful copy) rather than importing it directly (this extension
//  target's own cross-target boundary, same discipline that file's header documents). `PVInfo`,
//  NOT `PVPasskey`/`PVSuccess`, is this surface's own accent -- distinct from SAVE-01's `PVSuccess`
//  (Plan 44-04's save-confirmation screen), so SAVE-04's pixel proof can tell the two screens apart
//  in a screenshot alone.
//

import SwiftUI

struct GeneratePasswordOfferView: View {
    /// The pv-ffi-sourced candidate password to offer -- already generated by the time this view
    /// is constructed; this view never generates or re-derives it.
    let candidate: String
    let onUse: () -> Void
    let onCancel: () -> Void

    var body: some View {
        VStack(spacing: 0) {
            Spacer()

            VStack(spacing: 12) {
                Circle()
                    .fill(Color("PVInfo").opacity(0.14))
                    .frame(width: 64, height: 64)
                    .overlay(
                        Image(systemName: "wand.and.stars")
                            .font(.system(size: 26, weight: .semibold))
                            .foregroundStyle(Color("PVInfo"))
                    )
                    .accessibilityHidden(true)

                Text(verbatim: "Suggested password")
                    .font(.title2.weight(.semibold))
                    .foregroundStyle(Color("PVTextPrimary"))

                Text(verbatim: "Passkey Vault generated this password for you.")
                    .font(.subheadline)
                    .foregroundStyle(Color("PVTextMuted"))
                    .multilineTextAlignment(.center)
                    .fixedSize(horizontal: false, vertical: true)
            }
            .padding(.horizontal, 20)

            Spacer()

            Text(verbatim: candidate)
                .font(.system(.body, design: .monospaced).weight(.semibold))
                .foregroundStyle(Color("PVTextPrimary"))
                .multilineTextAlignment(.center)
                .padding(.horizontal, 16)
                .padding(.vertical, 14)
                .frame(maxWidth: .infinity)
                .background(
                    RoundedRectangle(cornerRadius: 11, style: .continuous)
                        .fill(Color("PVInfo").opacity(0.14))
                )
                .padding(.horizontal, 20)
                .accessibilityIdentifier("generatePassword.candidate")

            // Mirrors `PasskeyRegistrationConfirmView`'s own tinted-slot shape (14% tone tint,
            // 11pt radius) for the plain, non-playful security statement every generate offer
            // carries -- security UI is never playful, even here.
            HStack(alignment: .top, spacing: 9) {
                Circle()
                    .fill(Color("PVInfo"))
                    .frame(width: 8, height: 8)
                    .padding(.top, 5)
                    .accessibilityHidden(true)
                Text(verbatim: "Nothing is saved to your vault until you actually submit this form.")
                    .font(.footnote)
                    .foregroundStyle(Color("PVInfo"))
                    .fixedSize(horizontal: false, vertical: true)
                    .frame(maxWidth: .infinity, alignment: .leading)
            }
            .padding(.horizontal, 13)
            .padding(.vertical, 11)
            .frame(maxWidth: .infinity, alignment: .leading)
            .background(
                RoundedRectangle(cornerRadius: 11, style: .continuous)
                    .fill(Color("PVInfo").opacity(0.14))
            )
            .padding(.horizontal, 20)
            .padding(.top, 16)
            .padding(.bottom, 16)

            VStack(spacing: 9) {
                Button(action: onUse) {
                    Text(verbatim: "Use this password")
                        .font(.system(size: 17, weight: .semibold))
                        .frame(maxWidth: .infinity)
                        .frame(height: 50)
                }
                .background(Color("PVAccent"))
                .foregroundStyle(Color("PVOnAccent"))
                .clipShape(RoundedRectangle(cornerRadius: 12, style: .continuous))
                .accessibilityIdentifier("generatePassword.use")

                Button(action: onCancel) {
                    Text(verbatim: "Cancel")
                        .font(.system(size: 17, weight: .medium))
                        .frame(maxWidth: .infinity)
                        .frame(height: 44)
                }
                .foregroundStyle(Color("PVTextMuted"))
                .accessibilityIdentifier("generatePassword.cancel")
            }
            .padding(.horizontal, 20)
            .padding(.bottom, 10)
        }
        .frame(maxWidth: .infinity, maxHeight: .infinity)
        .background(Color("PVBackground"))
    }
}

#Preview {
    GeneratePasswordOfferView(candidate: "Tr4c3r-Gener8ted!", onUse: {}, onCancel: {})
}
