#!/usr/bin/env python3
"""totp-oracle.py -- an INDEPENDENT RFC 6238 implementation, Python standard
library only (`hmac`, `hashlib`, `struct`, `base64`) -- Phase 38, plan 38-10,
Task 3 (E-T1, `38-RESEARCH.md`).

Independent of `totp-rs` (the Rust crate `crates/pv-core/src/totp.rs` wraps)
and of Swift -- no code here is shared with, ported from, or generated by
either. That independence is the entire point: comparing the on-screen code
against a second, independently-written implementation of the specification
is what proves the FIRST implementation correct, and this script is that
second implementation.

STEP ZERO COMES FIRST, OR THE WHOLE COMPARISON IS WORTHLESS (38-RESEARCH.md's
own words). Run `--selftest` before trusting any other invocation of this
script: it reproduces RFC 6238 Appendix B's own published SHA1 vectors
(`crates/pv-core/src/totp.rs`'s test module carries the identical six pairs,
transcribed independently here, not imported) and exits non-zero if even one
mismatches. An unvalidated oracle proves nothing when compared against
anything else.

Mirrors `pv_core::totp::parse_algorithm`'s deliberate fail-safe: any
algorithm name other than "SHA256"/"SHA512" (including "SHA1" and any
unrecognized string) maps to SHA1. This script adds no validation the Rust
crate does not have, on either side of the boundary.

Usage:
    python3 scripts/totp-oracle.py --selftest
    python3 scripts/totp-oracle.py --secret <base32> --algorithm SHA1 \\
        --digits 6 --period 30 --time <unix-seconds> [--json]
"""

import argparse
import base64
import hashlib
import hmac
import json
import struct
import sys

# RFC 6238 Appendix B -- the SHA1 test secret is the base32 encoding of the
# 20-byte ASCII string "12345678901234567890". Six (time, expected-8-digit-
# code) pairs, transcribed independently from the specification text (and
# happening to match `crates/pv-core/src/totp.rs`'s own SHA1 test-vector
# list -- that agreement is what step zero below checks, not an import).
SELFTEST_SECRET = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"
SELFTEST_VECTORS = [
    (59, "94287082"),
    (1111111109, "07081804"),
    (1111111111, "14050471"),
    (1234567890, "89005924"),
    (2000000000, "69279037"),
    (20000000000, "65353130"),
]

_ALGORITHMS = {
    "SHA256": hashlib.sha256,
    "SHA512": hashlib.sha512,
}


def parse_algorithm(name):
    """Anything other than "SHA256"/"SHA512" -- including "SHA1" and any
    unrecognized string -- maps to SHA1. Mirrors
    `pv_core::totp::parse_algorithm` exactly; this is NOT this script adding
    its own default, it is reproducing the crate's documented fail-safe so
    the falsification arm (an unrecognized algorithm name) has something to
    agree with."""
    return _ALGORITHMS.get(name, hashlib.sha1)


def clean_and_decode_secret(secret_b32):
    """Strips whitespace and `=` padding before decoding -- mirrors
    `generate_code`'s own tolerance in `crates/pv-core/src/totp.rs` (a
    secret copy-pasted with padding, or with stray whitespace from a manual
    paste, must decode the same way on both sides of this comparison).
    Re-pads to a multiple of 8 characters afterward because Python's
    `base64.b32decode` requires it, not because the crate does."""
    cleaned = "".join(ch for ch in secret_b32 if not ch.isspace() and ch != "=")
    pad_len = (-len(cleaned)) % 8
    padded = cleaned + ("=" * pad_len)
    return base64.b32decode(padded, casefold=True)


def hotp(key, counter, digest_ctor, digits):
    """RFC 4226 HOTP: HMAC over the big-endian 8-byte counter, dynamic
    truncation (RFC 4226 §5.3), reduced mod 10**digits, zero-padded."""
    msg = struct.pack(">Q", counter)
    mac = hmac.new(key, msg, digest_ctor).digest()
    offset = mac[-1] & 0x0F
    code_int = (
        ((mac[offset] & 0x7F) << 24)
        | ((mac[offset + 1] & 0xFF) << 16)
        | ((mac[offset + 2] & 0xFF) << 8)
        | (mac[offset + 3] & 0xFF)
    )
    code = code_int % (10**digits)
    return str(code).zfill(digits)


def generate_code(secret_b32, algorithm, digits, period, unix_time_seconds):
    """RFC 6238 TOTP: HOTP at counter = floor(time / period). Returns
    (code, seconds_remaining) -- seconds_remaining is in `1..=period`, never
    0, matching `generate_code`'s own documented range in
    `crates/pv-core/src/totp.rs`."""
    if period <= 0:
        raise ValueError("period must be positive")
    key = clean_and_decode_secret(secret_b32)
    digest_ctor = parse_algorithm(algorithm)
    counter = unix_time_seconds // period
    code = hotp(key, counter, digest_ctor, digits)
    seconds_remaining = period - (unix_time_seconds % period)
    return code, seconds_remaining


def run_selftest():
    results = []
    for t, expected in SELFTEST_VECTORS:
        got, _ = generate_code(SELFTEST_SECRET, "SHA1", 8, 30, t)
        ok = got == expected
        results.append(ok)
        status = "PASS" if ok else "FAIL"
        print(f"[{status}] t={t} expected={expected} got={got}")
    matched = sum(1 for ok in results if ok)
    all_ok = all(results)
    print(f"SELFTEST: {'PASS' if all_ok else 'FAIL'} ({matched}/{len(SELFTEST_VECTORS)} RFC 6238 Appendix B vectors matched)")
    return all_ok


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--selftest", action="store_true", help="reproduce RFC 6238 Appendix B's published SHA1 vectors; run this FIRST")
    parser.add_argument("--secret", help="base32-encoded TOTP secret")
    parser.add_argument("--algorithm", default="SHA1", help="SHA1 (default) / SHA256 / SHA512; anything else falls back to SHA1")
    parser.add_argument("--digits", type=int, default=6)
    parser.add_argument("--period", type=int, default=30)
    parser.add_argument("--time", type=int, help="unix time in seconds")
    parser.add_argument("--json", action="store_true", help="emit {\"code\":...,\"secondsRemaining\":...} instead of plain text")
    args = parser.parse_args()

    if args.selftest:
        ok = run_selftest()
        sys.exit(0 if ok else 1)

    if args.secret is None or args.time is None:
        parser.error("--secret and --time are required unless --selftest is given")

    try:
        code, seconds_remaining = generate_code(
            args.secret, args.algorithm, args.digits, args.period, args.time
        )
    except Exception as exc:  # noqa: BLE001 -- CLI boundary, print and exit non-zero
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)

    if args.json:
        print(json.dumps({"code": code, "secondsRemaining": seconds_remaining}))
    else:
        print(f"code={code} secondsRemaining={seconds_remaining}")


if __name__ == "__main__":
    main()
