//! Phase 21 SC#4 regression tripwire: proves "an existing v0.3 account can
//! be given an identity keypair without re-encrypting a single byte of its
//! existing vault" against COMMITTED fixture data generated by the
//! pre-change `encrypt_item` code path (`crates/pv-core/tests/fixtures/
//! pre_v0_4_item.json`, see the sibling generator that produced it and was
//! then deleted — `git log --oneline -- crates/pv-core/tests/fixtures/`).
//!
//! This is deliberately NOT a same-run encrypt-then-decrypt round trip. A
//! same-run round trip would always use whatever the *current* code
//! produces on both sides of the equation and could never catch a
//! regression to `build_item_aad`'s byte layout or the
//! `AAD_ITEM_KEY_PREFIX`/`AAD_ITEM_DATA_PREFIX` constants — exactly the
//! failure mode this file exists to catch. By decrypting data that was
//! sealed by the OLD, pre-AAD-change code and committed to the repo, any
//! future accidental perturbation of the personal-scope AAD shape fails
//! this test loudly, by name, instead of silently corrupting every shipped
//! vault.
//!
//! This file does not modify or duplicate `crates/pv-core/src/items.rs`'s
//! own `#[cfg(test)] mod tests` (same-run round-trip coverage) — it is a
//! separate, complementary cross-cutting regression proof, mirroring
//! `crates/pv-provider/tests/response_shape.rs`'s placement precedent.

use pv_core::items::{decrypt_item, EncryptedItem};
use pv_core::keys::UserKey;

#[test]
fn pre_v0_4_item_decrypts_unchanged() {
    // Same fixed key/item_id/revision the (deleted) generator used.
    let uk = UserKey::from_bytes([0x42u8; 32]);
    let json = include_str!("fixtures/pre_v0_4_item.json");
    let item: EncryptedItem =
        serde_json::from_str(json).expect("committed fixture must be valid EncryptedItem JSON");

    let plaintext = decrypt_item(&uk, &item, "fixture-item-pre-v0.4", 1)
        .expect("pre-v0.4 fixture must decrypt unchanged under the frozen personal-scope AAD");

    assert_eq!(
        *plaintext,
        br#"{"type":"login","username":"fixture-user","password":"fixture-pre-v0.4-password"}"#
    );
}
